server:
    env: dev
    host: "0.0.0.0"
    port: "80"
    apipath: "/videos"
aws:
    s3bucket: "*****"
    cdnlink: "https://*****.cloudfront.net"
database:
    database: "videodatabase"
    user: "postgres"
    password: "postgres"
    host: "127.0.0.1"
    port: "5432"
